export const COUNTRY_GPS_SUCCESS = 'COUNTRY_GPS_SUCCESS';
export const FETCH_GPS_SUCCESS = 'FETCH_GPS_SUCCESS';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_COUNTRY_SETTINGS = 'GET_COUNTRY_SETTINGS';
export const PHONE_NUMBER = 'PHONE_NUMBER';
export const GET_DETAILS = 'GET_DETAILS';
export const GET_CREDIT_SUCCESS = 'GET_CREDIT_SUCCESS'
export const CREDIT_CALCULATE_SUCCESS = 'CREDIT_CALCULATE_SUCCESS'
export const CREDIT_APPLY_SUCCESS = 'CREDIT_APPLY_SUCCESS'
export const GET_AMOUNT = 'GET_AMOUNT'
export const GET_LOAN_DETAIL = 'GET_LOAN_DETAIL'
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
 



